---
version: "3"

services:
  mongodb:
    env_file: .env
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    volumes:
      - "${DB_DATA_DIR}:/data/db"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}"
    networks:
      - backend_net

  subscriptionrabbit:
    env_file: .env
    image: rabbitmq:3-management
    container_name: subscriptionrabbit
    restart: unless-stopped
    ports:
      - "15672:15672"
    environment:
      - "RABBITMQ_DEFAULT_USER=${MQ_USERNAME}"
      - "RABBITMQ_DEFAULT_PASS=${MQ_PASSWORD}"
    networks:
      - backend_net

  emailservice:
    container_name: emailservice
    image: email-service
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./packages/email-service/Dockerfile
    depends_on:
      - subscriptionrabbit
    networks:
      - backend_net

  subscriptionservice:
    container_name: subscriptionservice
    image: subscription-service
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./packages/subscription-service/Dockerfile
    depends_on:
      - subscriptionrabbit
      - mongodb
    networks:
      - backend_net
    links:
      - subscriptionrabbit
      - mongodb

  publicservice:
    container_name: publicservice
    image: public-service
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./packages/public-service/Dockerfile
    ports:
      - 3003:3003
    depends_on:
      - subscriptionservice
    links:
      - subscriptionservice
    networks:
      - backend_net
      - frontend_net

networks:
  backend_net:
    driver: bridge
  frontend_net:
    driver: bridge