default:
    server:
        port: 3000
    database:
        host: "localhost"
        port: 27018
        db: "subscriptions_db"
        user: "mongoadmin"
        pass: "dev_pass"
    mqmanager:
        host: "localhost"
        port: 5673
        queue: "campaign-subscription-queue"
        user: "mquser"
        pass: "mqpass"
    cacheprovider:
        ttl: 3600
