default:
    server:
        port: 3002
        tries: 5
    mqmanager:
        host: "localhost"
        port: 5673
        queue: "campaign-subscription-queue"
        user: "mquser"
        pass: "mqpass"
