default:
    server:
        port: 3002
        tries: 5
    mqmanager:
        host: "subscriptionrabbit"
        port: 5672
        queue: "campaign-subscription-queue"
        user: "mquser"
        pass: "mqpass"
