
on:
  push:
    branches: [ "test_deploy" ]
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'
  SERVER_PATH: /subscription-system

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'

    - name: yarn install
      run: |
        yarn install

    - name: yarn build
      run: |
        yarn build

    - name: yarn lint
      run: |
        yarn lint

    - name: yarn test
      run: |
        yarn test
    
    - name: Writing .env file
      uses: javajawa/create-envfile@v1
      with:
        file_name: .env
        envkey_DB_USERNAME: '${{ secrets.DB_USERNAME }}'
        envkey_DB_PASSWORD: '${{ secrets.DB_PASSWORD }}'
        envkey_DB_DATA_DIR: '${{ secrets.DB_DATA_DIR }}'
        envkey_MQ_USERNAME: '${{ secrets.MQ_USERNAME }}'
        envkey_MQ_PASSWORD: '${{ secrets.MQ_PASSWORD }}'
        envkey_CACHE_TTL: '${{ secrets.CACHE_TTL }}'
        envkey_DEPLOY_SHA1: '${{ github.sha }}'

    - name: Uploading files
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: ${{ secrets.DGOC_SSH_HOST }}
        key: ${{ secrets.DGOC_SSH_KEY }}
        user: ${{ secrets.DGOC_SSH_USER }}
        first_ssh: |
          mkdir -p "/pipeline/subscription-system"
        scp: |
          './packages/*' => "/pipeline/subscription-system/packages/"
          './scripts/*' => "/pipeline/subscription-system/scripts/"
          ./.env => "/pipeline/subscription-system/"
          ./docker-compose.yml => "/pipeline/subscription-system/"
          ./package.json => "/pipeline/subscription-system/"
          ./yarn.lock => "/pipeline/subscription-system/"
          ./tsconfig.base.json => "/pipeline/subscription-system/"
          ./.eslintrc.json => "/pipeline/subscription-system/"
        last_ssh: |
          ls -l /pipeline/subscription-system
    
    - name: Stop and remove the previous images/containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DGOC_SSH_HOST }}
        key: ${{ secrets.DGOC_SSH_KEY }}
        username: ${{ secrets.DGOC_SSH_USER }}
        script_stop: true
        script: |
          [[ ! -z $(docker ps -qf "name=service$") ]] && docker stop $(docker ps -qf "name=service$") || echo "No containers found"
          docker container prune -f
          [[ ! -z $(docker images "*-service" -q) ]] && docker rmi $(docker images "*-service" -q)  || echo "No images found"
    
    - name: Deploy services
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DGOC_SSH_HOST }}
        key: ${{ secrets.DGOC_SSH_KEY }}
        username: ${{ secrets.DGOC_SSH_USER }}
        script_stop: true
        timeout: "1m"
        command_timeout: "30m"
        script: |
            cd /pipeline/subscription-system
            docker compose up -d
            cd ..
            rm -fr /pipeline/subscription-system