
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: subscription-system-app
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '18.x'

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'

    - name: yarn install
      run: |
        yarn install

    - name: yarn build
      run: |
        yarn build

    - name: yarn lint
      run: |
        yarn lint

    - name: yarn test
      run: |
        yarn test
    
    - name: Writing .env file
      uses: javajawa/create-envfile@v1
      with:
        file_name: .env
        envkey_DB_USERNAME: '${{ secrets.DB_USERNAME }}'
        envkey_DB_PASSWORD: '${{ secrets.DB_PASSWORD }}'
        envkey_DB_DATA_DIR: '${{ secrets.DB_DATA_DIR }}'
        envkey_MQ_USERNAME: '${{ secrets.MQ_USERNAME }}'
        envkey_MQ_PASSWORD: '${{ secrets.MQ_PASSWORD }}'
        envkey_CACHE_TTL: '${{ secrets.CACHE_TTL }}'


    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: .

  build-images-and-deploy-to-azure:
    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd 

  # deploy:
  #   permissions:
  #     contents: none
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'Development'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #   - name: Download artifact from build job
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: node-app

  #   - name: 'Deploy to Azure WebApp'
  #     id: deploy-to-webapp
  #     uses: azure/webapps-deploy@v2
  #     with:
  #       app-name: ${{ env.AZURE_WEBAPP_NAME }}
  #       publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #       package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
